# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/CPE439/xadctest/xadctest.cache/wt [current_project]
set_property parent.project_path U:/CPE439/xadctest/xadctest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet u:/CPE439/Zybo-XADC-master/src/ip/xadc_wiz_0/xadc_wiz_0.dcp
set_property used_in_implementation false [get_files u:/CPE439/Zybo-XADC-master/src/ip/xadc_wiz_0/xadc_wiz_0.dcp]
read_verilog -library xil_defaultlib U:/CPE439/Zybo-XADC-master/src/hdl/XADCdemo.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc U:/CPE439/Zybo-XADC-master/src/constraints/ZYBO_Master.xdc
set_property used_in_implementation false [get_files U:/CPE439/Zybo-XADC-master/src/constraints/ZYBO_Master.xdc]


synth_design -top XADCdemo -part xc7z010clg400-1


write_checkpoint -force -noxdef XADCdemo.dcp

catch { report_utilization -file XADCdemo_utilization_synth.rpt -pb XADCdemo_utilization_synth.pb }
